# Generated by Django 2.0.4 on 2018-06-02 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InterRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('height', models.PositiveIntegerField(help_text='Altura en cm')),
                ('weight', models.PositiveIntegerField(help_text='Peso en gramos')),
                ('picture', models.ImageField(upload_to='picture_players')),
                ('position', models.CharField(choices=[('BA', 'Base'), ('ES', 'Escolta'), ('AL', 'Alero'), ('AP', 'Ala-pivot'), ('PI', 'Pivot')], max_length=60)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='RosterMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roster_local', to='basket.Roster')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Match')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roster_visita', to='basket.Roster')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_local', to='basket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_visit', to='basket.Team'),
        ),
        migrations.AddField(
            model_name='interroster',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterRoster_local', to='basket.Roster'),
        ),
        migrations.AddField(
            model_name='interroster',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.Match'),
        ),
        migrations.AddField(
            model_name='interroster',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterRoster_visit', to='basket.Roster'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rostermatch',
            unique_together={('local', 'match', 'visita')},
        ),
        migrations.AlterUniqueTogether(
            name='interroster',
            unique_together={('match', 'local', 'visit')},
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('user', 'team')},
        ),
    ]
