# Generated by Django 2.0.4 on 2018-06-01 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='roster',
        ),
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_local', to='basket.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='visit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_visit', to='basket.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team',)},
        ),
    ]
