# Generated by Django 2.0.4 on 2018-06-02 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20180601_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='RosterMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Roster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rostermatch',
            unique_together={('team', 'player')},
        ),
    ]
