# Generated by Django 2.0.4 on 2018-06-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20180602_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostermatch',
            name='local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='basket.Roster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rostermatch',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basket.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rostermatch',
            name='visita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='basket.Roster'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rostermatch',
            name='player',
        ),
        migrations.RemoveField(
            model_name='rostermatch',
            name='roster',
        ),
        migrations.RemoveField(
            model_name='rostermatch',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='rostermatch',
            unique_together={('local', 'match', 'visita')},
        ),
    ]
