# Generated by Django 2.0.4 on 2018-05-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='hour',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
